# meta file for fail2ban
---
galaxy_info:
  author: Albrekht Leonid
  description: Set up fail2ban
  license: MIT
  min_ansible_version: 2.2.0
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - system
    - networking
dependencies: []
